#!/bin/bash
# Clean up debug folder, and re-run cmake.
# Should be run only in debug folder.
# Luca Sciacovelli (luca.sciacovelli@ensam.eu)
# ---

# check current directory for safety
rightfold='debug'

curfold=${PWD##*/}
if [ "$curfold" != "$rightfold" ]
   then
   echo "-----------------------------------------------------------"
   echo 'ERROR! This script is meant to be run in ./'$rightfold 'folder'
   echo 'Current directory ./'$curfold
   echo 'Aborting for safety.'
   echo "-----------------------------------------------------------"
   exit 1
fi

# clean local folder
for f in ./*.*; do
    # check if the glob gets expanded to existing files.
   if [ -e "$f" ]; then
      echo "-----------------------------------------------------------"
      echo "Cleaning local folder files..."
      echo "-----------------------------------------------------------"
      \rm -v ./*.*
      \rm -v Makefile
   fi
    ## this is all we needed to know, so we can break after the first iteration
    break
done

# if [ -d CMakeFiles ]
#    then
#    echo "-----------------------------------------------------------"
#    echo "Cleaning local folder directories..."
#    echo "-----------------------------------------------------------"
#    \rm -v -r *
# fi

# clean binaries if present
for f in ../bin/*.x; do
    # check if the glob gets expanded to existing files.
   if [ -e "$f" ]; then
      echo "-----------------------------------------------------------"
      echo "Removing binary files in '../bin' ..."
      echo "-----------------------------------------------------------"
      \rm -v ../bin/*.x
   fi
    ## this is all we needed to know, so we can break after the first iteration
    break
done

# rebuild
echo "-----------------------------------------------------------"
echo "              CMAKE FOR TEST PROGRAM                       "
echo "-----------------------------------------------------------"
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_RULE_MESSAGES:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ../src
echo "-----------------------------------------------------------"
echo "Done!"
echo "-----------------------------------------------------------"